/**
 * Lead field choices matching Django backend
 * @module lib/constants/lead-choices
 */

/** @type {{ value: string, label: string }[]} */
export const INDUSTRIES = [
  { value: '', label: '请选择行业' },
  { value: 'ADVERTISING', label: '广告' },
  { value: 'AGRICULTURE', label: '农业' },
  { value: 'APPAREL & ACCESSORIES', label: '服装与配饰' },
  { value: 'AUTOMOTIVE', label: '汽车' },
  { value: 'BANKING', label: '银行' },
  { value: 'BIOTECHNOLOGY', label: '生物技术' },
  { value: 'BUILDING MATERIALS & EQUIPMENT', label: '建筑材料与设备' },
  { value: 'CHEMICAL', label: '化工' },
  { value: 'COMPUTER', label: '计算机' },
  { value: 'EDUCATION', label: '教育' },
  { value: 'ELECTRONICS', label: '电子' },
  { value: 'ENERGY', label: '能源' },
  { value: 'ENTERTAINMENT & LEISURE', label: '娱乐与休闲' },
  { value: 'FINANCE', label: '金融' },
  { value: 'FOOD & BEVERAGE', label: '食品与饮料' },
  { value: 'GROCERY', label: '杂货' },
  { value: 'HEALTHCARE', label: '医疗保健' },
  { value: 'INSURANCE', label: '保险' },
  { value: 'LEGAL', label: '法律' },
  { value: 'MANUFACTURING', label: '制造业' },
  { value: 'PUBLISHING', label: '出版' },
  { value: 'REAL ESTATE', label: '房地产' },
  { value: 'SERVICE', label: '服务' },
  { value: 'SOFTWARE', label: '软件' },
  { value: 'SPORTS', label: '体育' },
  { value: 'TECHNOLOGY', label: '科技' },
  { value: 'TELECOMMUNICATIONS', label: '电信' },
  { value: 'TELEVISION', label: '电视' },
  { value: 'TRANSPORTATION', label: '交通运输' },
  { value: 'VENTURE CAPITAL', label: '风险投资' }
];

/** @type {{ value: string, label: string }[]} */
export const COUNTRIES = [
	{ value: '', label: '请选择国家' },
	{ value: 'US', label: '美国' },
	{ value: 'GB', label: '英国' },
	{ value: 'CA', label: '加拿大' },
	{ value: 'AU', label: '澳大利亚' },
	{ value: 'DE', label: '德国' },
	{ value: 'FR', label: '法国' },
	{ value: 'IN', label: '印度' },
	{ value: 'CN', label: '中国' },
	{ value: 'JP', label: '日本' },
	{ value: 'BR', label: '巴西' },
	{ value: 'MX', label: '墨西哥' },
	{ value: 'ES', label: '西班牙' },
	{ value: 'IT', label: '意大利' },
	{ value: 'NL', label: '荷兰' },
	{ value: 'SE', label: '瑞典' },
	{ value: 'CH', label: '瑞士' },
	{ value: 'SG', label: '新加坡' },
	{ value: 'AE', label: '阿联酋' },
	{ value: 'AF', label: '阿富汗' },
	{ value: 'AL', label: '阿尔巴尼亚' },
	{ value: 'DZ', label: '阿尔及利亚' },
	{ value: 'AR', label: '阿根廷' },
	{ value: 'AM', label: '亚美尼亚' },
	{ value: 'AT', label: '奥地利' },
	{ value: 'AZ', label: '阿塞拜疆' },
	{ value: 'BH', label: '巴林' },
	{ value: 'BD', label: '孟加拉国' },
	{ value: 'BY', label: '白俄罗斯' },
	{ value: 'BE', label: '比利时' },
	{ value: 'BG', label: '保加利亚' },
	{ value: 'CL', label: '智利' },
	{ value: 'CO', label: '哥伦比亚' },
	{ value: 'CR', label: '哥斯达黎加' },
	{ value: 'HR', label: '克罗地亚' },
	{ value: 'CY', label: '塞浦路斯' },
	{ value: 'CZ', label: '捷克共和国' },
	{ value: 'DK', label: '丹麦' },
	{ value: 'EG', label: '埃及' },
	{ value: 'EE', label: '爱沙尼亚' },
	{ value: 'FI', label: '芬兰' },
	{ value: 'GE', label: '格鲁吉亚' },
	{ value: 'GR', label: '希腊' },
	{ value: 'HK', label: '香港' },
	{ value: 'HU', label: '匈牙利' },
	{ value: 'IS', label: '冰岛' },
	{ value: 'ID', label: '印度尼西亚' },
	{ value: 'IR', label: '伊朗' },
	{ value: 'IQ', label: '伊拉克' },
	{ value: 'IE', label: '爱尔兰' },
	{ value: 'IL', label: '以色列' },
	{ value: 'JO', label: '约旦' },
	{ value: 'KZ', label: '哈萨克斯坦' },
	{ value: 'KE', label: '肯尼亚' },
	{ value: 'KW', label: '科威特' },
	{ value: 'LV', label: '拉脱维亚' },
	{ value: 'LB', label: '黎巴嫩' },
	{ value: 'LT', label: '立陶宛' },
	{ value: 'LU', label: '卢森堡' },
	{ value: 'MY', label: '马来西亚' },
	{ value: 'MT', label: '马耳他' },
	{ value: 'MA', label: '摩洛哥' },
	{ value: 'NZ', label: '新西兰' },
	{ value: 'NG', label: '尼日利亚' },
	{ value: 'NO', label: '挪威' },
	{ value: 'OM', label: '阿曼' },
	{ value: 'PK', label: '巴基斯坦' },
	{ value: 'PE', label: '秘鲁' },
	{ value: 'PH', label: '菲律宾' },
	{ value: 'PL', label: '波兰' },
	{ value: 'PT', label: '葡萄牙' },
	{ value: 'QA', label: '卡塔尔' },
	{ value: 'RO', label: '罗马尼亚' },
	{ value: 'RU', label: '俄罗斯' },
	{ value: 'SA', label: '沙特阿拉伯' },
	{ value: 'RS', label: '塞尔维亚' },
	{ value: 'SK', label: '斯洛伐克' },
	{ value: 'SI', label: '斯洛文尼亚' },
	{ value: 'ZA', label: '南非' },
	{ value: 'KR', label: '韩国' },
	{ value: 'LK', label: '斯里兰卡' },
	{ value: 'TW', label: '台湾' },
	{ value: 'TH', label: '泰国' },
	{ value: 'TR', label: '土耳其' },
	{ value: 'UA', label: '乌克兰' },
	{ value: 'UY', label: '乌拉圭' },
	{ value: 'VE', label: '委内瑞拉' },
	{ value: 'VN', label: '越南' }
];
