# Generated by Django 4.2.27 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_board_created_by_alter_board_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-created_at',), 'verbose_name': '看板', 'verbose_name_plural': '看板'},
        ),
        migrations.AlterModelOptions(
            name='boardcolumn',
            options={'ordering': ('order',), 'verbose_name': '看板列', 'verbose_name_plural': '看板列'},
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'verbose_name': '看板成员', 'verbose_name_plural': '看板成员'},
        ),
        migrations.AlterModelOptions(
            name='boardtask',
            options={'ordering': ('order',), 'verbose_name': '看板任务', 'verbose_name_plural': '看板任务'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-due_date',), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardtask',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高')], max_length=50, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', '新建'), ('In Progress', '进行中'), ('Completed', '已完成')], max_length=50, verbose_name='status'),
        ),
    ]
