# Generated by Django 4.2.27 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_alter_opportunity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ('-created_at',), 'verbose_name': '商机', 'verbose_name_plural': '商机'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='预计成交日期'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('INR', '印度卢比'), ('CAD', '加拿大元'), ('AUD', '澳大利亚元'), ('JPY', '日元'), ('CNY', '人民币'), ('CHF', '瑞士法郎'), ('SGD', '新加坡元'), ('AED', '阿联酋迪拉姆'), ('BRL', '巴西雷亚尔'), ('MXN', '墨西哥比索')], max_length=3, null=True, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('NONE', '无'), ('CALL', '电话'), ('EMAIL', '邮件'), ('EXISTING CUSTOMER', '现有客户'), ('PARTNER', '合作伙伴'), ('PUBLIC RELATIONS', '公共关系'), ('CAMPAIGN', '营销活动'), ('WEBSITE', '网站'), ('OTHER', '其他')], max_length=255, null=True, verbose_name='线索来源'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='商机名称'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('NEW_BUSINESS', '新业务'), ('EXISTING_BUSINESS', '现有业务'), ('RENEWAL', '续约'), ('UPSELL', '追加销售'), ('CROSS_SELL', '交叉销售')], max_length=64, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='概率 (%)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('PROSPECTING', '潜在客户'), ('QUALIFICATION', '资格审核'), ('PROPOSAL', '提案'), ('NEGOTIATION', '谈判'), ('CLOSED_WON', '已赢得'), ('CLOSED_LOST', '已丢失')], default='PROSPECTING', max_length=64, verbose_name='阶段'),
        ),
    ]
