# Generated by Django 4.2.27 on 2025-12-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_currency_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Invoice Product', 'verbose_name_plural': 'Invoice Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='invoice_product',
        ),
    ]
