# Generated by Django 4.2.27 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',), 'verbose_name': '发票', 'verbose_name_plural': '发票'},
        ),
        migrations.AlterModelOptions(
            name='invoicehistory',
            options={'ordering': ('-created_at',), 'verbose_name': '发票历史记录', 'verbose_name_plural': '发票历史记录'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ('order',), 'verbose_name': '发票行项目', 'verbose_name_plural': '发票行项目'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': '发票产品', 'verbose_name_plural': '发票产品'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('INR', '印度卢比'), ('CAD', '加拿大元'), ('AUD', '澳大利亚元'), ('JPY', '日元'), ('CNY', '人民币'), ('CHF', '瑞士法郎'), ('SGD', '新加坡元'), ('AED', '阿联酋迪拉姆'), ('BRL', '巴西雷亚尔'), ('MXN', '墨西哥比索')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='发票编号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_title',
            field=models.CharField(max_length=50, verbose_name='发票标题'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', '草稿'), ('Sent', '已发送'), ('Paid', '已支付'), ('Pending', '待处理'), ('Cancelled', '已取消')], default='Draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('INR', '印度卢比'), ('CAD', '加拿大元'), ('AUD', '澳大利亚元'), ('JPY', '日元'), ('CNY', '人民币'), ('CHF', '瑞士法郎'), ('SGD', '新加坡元'), ('AED', '阿联酋迪拉姆'), ('BRL', '巴西雷亚尔'), ('MXN', '墨西哥比索')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='发票编号'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='invoice_title',
            field=models.CharField(max_length=50, verbose_name='发票标题'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='status',
            field=models.CharField(choices=[('Draft', '草稿'), ('Sent', '已发送'), ('Paid', '已支付'), ('Pending', '待处理'), ('Cancelled', '已取消')], default='Draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('INR', '印度卢比'), ('CAD', '加拿大元'), ('AUD', '澳大利亚元'), ('JPY', '日元'), ('CNY', '人民币'), ('CHF', '瑞士法郎'), ('SGD', '新加坡元'), ('AED', '阿联酋迪拉姆'), ('BRL', '巴西雷亚尔'), ('MXN', '墨西哥比索')], max_length=3, null=True),
        ),
    ]
