# Generated by Django 4.2.27 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_enable_rls_product_invoice_line_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created_at',), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_at',), 'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='apisettings',
            options={'ordering': ('-created_at',), 'verbose_name': 'API设置', 'verbose_name_plural': 'API设置'},
        ),
        migrations.AlterModelOptions(
            name='attachments',
            options={'ordering': ('-created_at',), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='commentfiles',
            options={'ordering': ('-created_at',), 'verbose_name': '评论文件', 'verbose_name_plural': '评论文件'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_at',), 'verbose_name': '文档', 'verbose_name_plural': '文档'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ('-created_at',), 'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',), 'verbose_name': '个人资料', 'verbose_name_plural': '个人资料'},
        ),
        migrations.AlterModelOptions(
            name='sessiontoken',
            options={'ordering': ('-created_at',), 'verbose_name': '会话令牌', 'verbose_name_plural': '会话令牌'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('-created_at',), 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ('-created_at',), 'verbose_name': '团队', 'verbose_name_plural': '团队'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_active',), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('COMMENT', '评论'), ('ASSIGN', '分配')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='entity_type',
            field=models.CharField(choices=[('Account', '客户'), ('Lead', '线索'), ('Contact', '联系人'), ('Opportunity', '商机'), ('Case', '案例'), ('Task', '任务'), ('Invoice', '发票'), ('Event', '事件'), ('Document', '文档'), ('Team', '团队')], max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('GB', '英国'), ('AF', '阿富汗'), ('AX', '奥兰群岛'), ('AL', '阿尔巴尼亚'), ('DZ', '阿尔及利亚'), ('AS', '美属萨摩亚'), ('AD', '安道尔'), ('AO', '安哥拉'), ('AI', '安圭拉'), ('AQ', '南极洲'), ('AG', '安提瓜和巴布达'), ('AR', '阿根廷'), ('AM', '亚美尼亚'), ('AW', '阿鲁巴'), ('AU', '澳大利亚'), ('AT', '奥地利'), ('AZ', '阿塞拜疆'), ('BS', '巴哈马'), ('BH', '巴林'), ('BD', '孟加拉国'), ('BB', '巴巴多斯'), ('BY', '白俄罗斯'), ('BE', '比利时'), ('BZ', '伯利兹'), ('BJ', '贝宁'), ('BM', '百慕大'), ('BT', '不丹'), ('BO', '玻利维亚'), ('BA', '波斯尼亚和黑塞哥维那'), ('BW', '博茨瓦纳'), ('BV', '布维岛'), ('BR', '巴西'), ('IO', '英属印度洋领地'), ('BN', '文莱'), ('BG', '保加利亚'), ('BF', '布基纳法索'), ('BI', '布隆迪'), ('KH', '柬埔寨'), ('CM', '喀麦隆'), ('CA', '加拿大'), ('CV', '佛得角'), ('KY', '开曼群岛'), ('CF', '中非共和国'), ('TD', '乍得'), ('CL', '智利'), ('CN', '中国'), ('CX', '圣诞岛'), ('CC', '科科斯（基林）群岛'), ('CO', '哥伦比亚'), ('KM', '科摩罗'), ('CG', '刚果（布）'), ('CD', '刚果（金）'), ('CK', '库克群岛'), ('CR', '哥斯达黎加'), ('CI', '科特迪瓦'), ('HR', '克罗地亚'), ('CU', '古巴'), ('CY', '塞浦路斯'), ('CZ', '捷克共和国'), ('DK', '丹麦'), ('DJ', '吉布提'), ('DM', '多米尼克'), ('DO', '多米尼加共和国'), ('EC', '厄瓜多尔'), ('EG', '埃及'), ('SV', '萨尔瓦多'), ('GQ', '赤道几内亚'), ('ER', '厄立特里亚'), ('EE', '爱沙尼亚'), ('ET', '埃塞俄比亚'), ('FK', '福克兰群岛（马尔维纳斯）'), ('FO', '法罗群岛'), ('FJ', '斐济'), ('FI', '芬兰'), ('FR', '法国'), ('GF', '法属圭亚那'), ('PF', '法属波利尼西亚'), ('TF', '法属南部领地'), ('GA', '加蓬'), ('GM', '冈比亚'), ('GE', '格鲁吉亚'), ('DE', '德国'), ('GH', '加纳'), ('GI', '直布罗陀'), ('GR', '希腊'), ('GL', '格陵兰'), ('GD', '格林纳达'), ('GP', '瓜德罗普'), ('GU', '关岛'), ('GT', '危地马拉'), ('GG', '根西岛'), ('GN', '几内亚'), ('GW', '几内亚比绍'), ('GY', '圭亚那'), ('HT', '海地'), ('HM', '赫德岛和麦克唐纳群岛'), ('VA', '梵蒂冈'), ('HN', '洪都拉斯'), ('HK', '香港'), ('HU', '匈牙利'), ('IS', '冰岛'), ('IN', '印度'), ('ID', '印度尼西亚'), ('IR', '伊朗'), ('IQ', '伊拉克'), ('IE', '爱尔兰'), ('IM', '马恩岛'), ('IL', '以色列'), ('IT', '意大利'), ('JM', '牙买加'), ('JP', '日本'), ('JE', '泽西岛'), ('JO', '约旦'), ('KZ', '哈萨克斯坦'), ('KE', '肯尼亚'), ('KI', '基里巴斯'), ('KP', '朝鲜'), ('KR', '韩国'), ('KW', '科威特'), ('KG', '吉尔吉斯斯坦'), ('LA', '老挝'), ('LV', '拉脱维亚'), ('LB', '黎巴嫩'), ('LS', '莱索托'), ('LR', '利比里亚'), ('LY', '利比亚'), ('LI', '列支敦士登'), ('LT', '立陶宛'), ('LU', '卢森堡'), ('MO', '澳门'), ('MK', '北马其顿'), ('MG', '马达加斯加'), ('MW', '马拉维'), ('MY', '马来西亚'), ('MV', '马尔代夫'), ('ML', '马里'), ('MT', '马耳他'), ('MH', '马绍尔群岛'), ('MQ', '马提尼克'), ('MR', '毛里塔尼亚'), ('MU', '毛里求斯'), ('YT', '马约特'), ('MX', '墨西哥'), ('FM', '密克罗尼西亚'), ('MD', '摩尔多瓦'), ('MC', '摩纳哥'), ('MN', '蒙古'), ('ME', '黑山'), ('MS', '蒙特塞拉特'), ('MA', '摩洛哥'), ('MZ', '莫桑比克'), ('MM', '缅甸'), ('NA', '纳米比亚'), ('NR', '瑙鲁'), ('NP', '尼泊尔'), ('NL', '荷兰'), ('AN', '荷属安的列斯'), ('NC', '新喀里多尼亚'), ('NZ', '新西兰'), ('NI', '尼加拉瓜'), ('NE', '尼日尔'), ('NG', '尼日利亚'), ('NU', '纽埃'), ('NF', '诺福克岛'), ('MP', '北马里亚纳群岛'), ('NO', '挪威'), ('OM', '阿曼'), ('PK', '巴基斯坦'), ('PW', '帕劳'), ('PS', '巴勒斯坦领土'), ('PA', '巴拿马'), ('PG', '巴布亚新几内亚'), ('PY', '巴拉圭'), ('PE', '秘鲁'), ('PH', '菲律宾'), ('PN', '皮特凯恩群岛'), ('PL', '波兰'), ('PT', '葡萄牙'), ('PR', '波多黎各'), ('QA', '卡塔尔'), ('RE', '留尼汪'), ('RO', '罗马尼亚'), ('RU', '俄罗斯'), ('RW', '卢旺达'), ('BL', '圣巴泰勒米'), ('SH', '圣赫勒拿'), ('KN', '圣基茨和尼维斯'), ('LC', '圣卢西亚'), ('MF', '圣马丁'), ('PM', '圣皮埃尔和密克隆'), ('VC', '圣文森特和格林纳丁斯'), ('WS', '萨摩亚'), ('SM', '圣马力诺'), ('ST', '圣多美和普林西比'), ('SA', '沙特阿拉伯'), ('SN', '塞内加尔'), ('RS', '塞尔维亚'), ('SC', '塞舌尔'), ('SL', '塞拉利昂'), ('SG', '新加坡'), ('SK', '斯洛伐克'), ('SI', '斯洛文尼亚'), ('SB', '所罗门群岛'), ('SO', '索马里'), ('ZA', '南非'), ('GS', '南乔治亚和南桑威奇群岛'), ('ES', '西班牙'), ('LK', '斯里兰卡'), ('SD', '苏丹'), ('SR', '苏里南'), ('SJ', '斯瓦尔巴和扬马延'), ('SZ', '斯威士兰'), ('SE', '瑞典'), ('CH', '瑞士'), ('SY', '叙利亚'), ('TW', '台湾（中国省份）'), ('TJ', '塔吉克斯坦'), ('TZ', '坦桑尼亚'), ('TH', '泰国'), ('TL', '东帝汶'), ('TG', '多哥'), ('TK', '托克劳'), ('TO', '汤加'), ('TT', '特立尼达和多巴哥'), ('TN', '突尼斯'), ('TR', '土耳其'), ('TM', '土库曼斯坦'), ('TC', '特克斯和凯科斯群岛'), ('TV', '图瓦卢'), ('UG', '乌干达'), ('UA', '乌克兰'), ('AE', '阿拉伯联合酋长国'), ('US', '美国'), ('UM', '美国本土外小岛屿'), ('UY', '乌拉圭'), ('UZ', '乌兹别克斯坦'), ('VU', '瓦努阿图'), ('VE', '委内瑞拉'), ('VN', '越南'), ('VG', '英属维尔京群岛'), ('VI', '美属维尔京群岛'), ('WF', '瓦利斯和富图纳'), ('EH', '西撒哈拉'), ('YE', '也门'), ('ZM', '赞比亚'), ('ZW', '津巴布韦')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=55, verbose_name='街道'),
        ),
        migrations.AlterField(
            model_name='commentfiles',
            name='comment_file',
            field=models.FileField(blank=True, null=True, upload_to='CommentFiles', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='org',
            name='default_country',
            field=models.CharField(blank=True, choices=[('GB', '英国'), ('AF', '阿富汗'), ('AX', '奥兰群岛'), ('AL', '阿尔巴尼亚'), ('DZ', '阿尔及利亚'), ('AS', '美属萨摩亚'), ('AD', '安道尔'), ('AO', '安哥拉'), ('AI', '安圭拉'), ('AQ', '南极洲'), ('AG', '安提瓜和巴布达'), ('AR', '阿根廷'), ('AM', '亚美尼亚'), ('AW', '阿鲁巴'), ('AU', '澳大利亚'), ('AT', '奥地利'), ('AZ', '阿塞拜疆'), ('BS', '巴哈马'), ('BH', '巴林'), ('BD', '孟加拉国'), ('BB', '巴巴多斯'), ('BY', '白俄罗斯'), ('BE', '比利时'), ('BZ', '伯利兹'), ('BJ', '贝宁'), ('BM', '百慕大'), ('BT', '不丹'), ('BO', '玻利维亚'), ('BA', '波斯尼亚和黑塞哥维那'), ('BW', '博茨瓦纳'), ('BV', '布维岛'), ('BR', '巴西'), ('IO', '英属印度洋领地'), ('BN', '文莱'), ('BG', '保加利亚'), ('BF', '布基纳法索'), ('BI', '布隆迪'), ('KH', '柬埔寨'), ('CM', '喀麦隆'), ('CA', '加拿大'), ('CV', '佛得角'), ('KY', '开曼群岛'), ('CF', '中非共和国'), ('TD', '乍得'), ('CL', '智利'), ('CN', '中国'), ('CX', '圣诞岛'), ('CC', '科科斯（基林）群岛'), ('CO', '哥伦比亚'), ('KM', '科摩罗'), ('CG', '刚果（布）'), ('CD', '刚果（金）'), ('CK', '库克群岛'), ('CR', '哥斯达黎加'), ('CI', '科特迪瓦'), ('HR', '克罗地亚'), ('CU', '古巴'), ('CY', '塞浦路斯'), ('CZ', '捷克共和国'), ('DK', '丹麦'), ('DJ', '吉布提'), ('DM', '多米尼克'), ('DO', '多米尼加共和国'), ('EC', '厄瓜多尔'), ('EG', '埃及'), ('SV', '萨尔瓦多'), ('GQ', '赤道几内亚'), ('ER', '厄立特里亚'), ('EE', '爱沙尼亚'), ('ET', '埃塞俄比亚'), ('FK', '福克兰群岛（马尔维纳斯）'), ('FO', '法罗群岛'), ('FJ', '斐济'), ('FI', '芬兰'), ('FR', '法国'), ('GF', '法属圭亚那'), ('PF', '法属波利尼西亚'), ('TF', '法属南部领地'), ('GA', '加蓬'), ('GM', '冈比亚'), ('GE', '格鲁吉亚'), ('DE', '德国'), ('GH', '加纳'), ('GI', '直布罗陀'), ('GR', '希腊'), ('GL', '格陵兰'), ('GD', '格林纳达'), ('GP', '瓜德罗普'), ('GU', '关岛'), ('GT', '危地马拉'), ('GG', '根西岛'), ('GN', '几内亚'), ('GW', '几内亚比绍'), ('GY', '圭亚那'), ('HT', '海地'), ('HM', '赫德岛和麦克唐纳群岛'), ('VA', '梵蒂冈'), ('HN', '洪都拉斯'), ('HK', '香港'), ('HU', '匈牙利'), ('IS', '冰岛'), ('IN', '印度'), ('ID', '印度尼西亚'), ('IR', '伊朗'), ('IQ', '伊拉克'), ('IE', '爱尔兰'), ('IM', '马恩岛'), ('IL', '以色列'), ('IT', '意大利'), ('JM', '牙买加'), ('JP', '日本'), ('JE', '泽西岛'), ('JO', '约旦'), ('KZ', '哈萨克斯坦'), ('KE', '肯尼亚'), ('KI', '基里巴斯'), ('KP', '朝鲜'), ('KR', '韩国'), ('KW', '科威特'), ('KG', '吉尔吉斯斯坦'), ('LA', '老挝'), ('LV', '拉脱维亚'), ('LB', '黎巴嫩'), ('LS', '莱索托'), ('LR', '利比里亚'), ('LY', '利比亚'), ('LI', '列支敦士登'), ('LT', '立陶宛'), ('LU', '卢森堡'), ('MO', '澳门'), ('MK', '北马其顿'), ('MG', '马达加斯加'), ('MW', '马拉维'), ('MY', '马来西亚'), ('MV', '马尔代夫'), ('ML', '马里'), ('MT', '马耳他'), ('MH', '马绍尔群岛'), ('MQ', '马提尼克'), ('MR', '毛里塔尼亚'), ('MU', '毛里求斯'), ('YT', '马约特'), ('MX', '墨西哥'), ('FM', '密克罗尼西亚'), ('MD', '摩尔多瓦'), ('MC', '摩纳哥'), ('MN', '蒙古'), ('ME', '黑山'), ('MS', '蒙特塞拉特'), ('MA', '摩洛哥'), ('MZ', '莫桑比克'), ('MM', '缅甸'), ('NA', '纳米比亚'), ('NR', '瑙鲁'), ('NP', '尼泊尔'), ('NL', '荷兰'), ('AN', '荷属安的列斯'), ('NC', '新喀里多尼亚'), ('NZ', '新西兰'), ('NI', '尼加拉瓜'), ('NE', '尼日尔'), ('NG', '尼日利亚'), ('NU', '纽埃'), ('NF', '诺福克岛'), ('MP', '北马里亚纳群岛'), ('NO', '挪威'), ('OM', '阿曼'), ('PK', '巴基斯坦'), ('PW', '帕劳'), ('PS', '巴勒斯坦领土'), ('PA', '巴拿马'), ('PG', '巴布亚新几内亚'), ('PY', '巴拉圭'), ('PE', '秘鲁'), ('PH', '菲律宾'), ('PN', '皮特凯恩群岛'), ('PL', '波兰'), ('PT', '葡萄牙'), ('PR', '波多黎各'), ('QA', '卡塔尔'), ('RE', '留尼汪'), ('RO', '罗马尼亚'), ('RU', '俄罗斯'), ('RW', '卢旺达'), ('BL', '圣巴泰勒米'), ('SH', '圣赫勒拿'), ('KN', '圣基茨和尼维斯'), ('LC', '圣卢西亚'), ('MF', '圣马丁'), ('PM', '圣皮埃尔和密克隆'), ('VC', '圣文森特和格林纳丁斯'), ('WS', '萨摩亚'), ('SM', '圣马力诺'), ('ST', '圣多美和普林西比'), ('SA', '沙特阿拉伯'), ('SN', '塞内加尔'), ('RS', '塞尔维亚'), ('SC', '塞舌尔'), ('SL', '塞拉利昂'), ('SG', '新加坡'), ('SK', '斯洛伐克'), ('SI', '斯洛文尼亚'), ('SB', '所罗门群岛'), ('SO', '索马里'), ('ZA', '南非'), ('GS', '南乔治亚和南桑威奇群岛'), ('ES', '西班牙'), ('LK', '斯里兰卡'), ('SD', '苏丹'), ('SR', '苏里南'), ('SJ', '斯瓦尔巴和扬马延'), ('SZ', '斯威士兰'), ('SE', '瑞典'), ('CH', '瑞士'), ('SY', '叙利亚'), ('TW', '台湾（中国省份）'), ('TJ', '塔吉克斯坦'), ('TZ', '坦桑尼亚'), ('TH', '泰国'), ('TL', '东帝汶'), ('TG', '多哥'), ('TK', '托克劳'), ('TO', '汤加'), ('TT', '特立尼达和多巴哥'), ('TN', '突尼斯'), ('TR', '土耳其'), ('TM', '土库曼斯坦'), ('TC', '特克斯和凯科斯群岛'), ('TV', '图瓦卢'), ('UG', '乌干达'), ('UA', '乌克兰'), ('AE', '阿拉伯联合酋长国'), ('US', '美国'), ('UM', '美国本土外小岛屿'), ('UY', '乌拉圭'), ('UZ', '乌兹别克斯坦'), ('VU', '瓦努阿图'), ('VE', '委内瑞拉'), ('VN', '越南'), ('VG', '英属维尔京群岛'), ('VI', '美属维尔京群岛'), ('WF', '瓦利斯和富图纳'), ('EH', '西撒哈拉'), ('YE', '也门'), ('ZM', '赞比亚'), ('ZW', '津巴布韦')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='default_currency',
            field=models.CharField(choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('INR', '印度卢比'), ('CAD', '加拿大元'), ('AUD', '澳大利亚元'), ('JPY', '日元'), ('CNY', '人民币'), ('CHF', '瑞士法郎'), ('SGD', '新加坡元'), ('AED', '阿联酋迪拉姆'), ('BRL', '巴西雷亚尔'), ('MXN', '墨西哥比索')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理员'), ('USER', '用户')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='员工状态'),
        ),
    ]
