# Generated by Django 4.2.27 on 2025-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_created_by_alter_case_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-created_at',), 'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('-created_at',), 'verbose_name': '解决方案', 'verbose_name_plural': '解决方案'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Question', '问题'), ('Incident', '事件'), ('Problem', '问题')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('Low', '低'), ('Normal', '普通'), ('High', '高'), ('Urgent', '紧急')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('New', '新建'), ('Assigned', '已分配'), ('Pending', '待处理'), ('Closed', '已关闭'), ('Rejected', '已拒绝'), ('Duplicate', '重复')], max_length=64),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('reviewed', '已审核'), ('approved', '已批准')], default='draft', max_length=20),
        ),
    ]
